export const CLEAR_MOVIE = 'CLEAR_MOVIE';
export const GET_MOVIE = 'GET_MOVIE_REQUEST';
export const GET_MOVIES = 'GET_MOVIES_REQUEST';
export const CREATE_MOVIE = 'CREATE_MOVIE_REQUEST';
export const DELETE_MOVIE = 'DELETE_MOVIE_REQUEST';
export const IMPORT_MOVIES = 'IMPORT_MOVIES_REQUEST';
